# What are your current data practices and setup?
## Session 2 - 8/28/2025 {.unnumbered .unlisted}

## Overview {.unnumbered}

Participants will be provided a facilitator’s guide to document existing tools, culture, and infrastructure at their own organization.
They will evaluate if current practices set them up for success in the CRM migration.
Using the guide, each team will map their DARCIs to clarify roles and capacity for data management at their respective organization.

## Pre-Reading {.unnumbered}

### Required {.unnumbered}
- [Sketching the Blueprint of Your Data Infrastructure](https://move-coop.github.io/pathways-implementation-toolkit/data-infrastructure.html){.external target="_blank"} of the Pathways to Power: Implementing Metrics for Base Building and Leadership Development Toolkit

### Optional {.unnumbered}
- [How to Build a Marketing Technology (Martech) Stack That'll Grow With You](https://blog.hubspot.com/marketing/how-to-build-a-marketing-stack){.external target="_blank"}
- [4 Key Reasons to Build a Data Culture](https://www.dataversity.net/4-key-reasons-to-build-a-data-culture/){.external target="_blank"}

## Recording {.unnumbered}

{{< video https://www.youtube.com/embed/vUpU9PVkp2I >}}

## Slides {.unnumbered}

<iframe src="https://docs.google.com/presentation/d/1Fnw635x2F5kvADeI-H1BCaNg4NmVrm8JLU2vEPz0tJQ/embed#slide=id.g317fdab4a59_0_26" width="100%" height="480" allow="autoplay">

</iframe>

If you would like to make a copy you can find the slides [here](https://docs.google.com/presentation/d/1Fnw635x2F5kvADeI-H1BCaNg4NmVrm8JLU2vEPz0tJQ){.external target="_blank"}

## Takeaway {.unnumbered}

* Steps 1, 2a and 2b of the [Data Map Visualization for Basebuilding and Leadership Development Metrics](https://www.canva.com/design/DAGOguXd_S4/lkyv0tTpoQxJYQ-ngplm9A/edit){.external target="_blank"}
* [Tech Stack Mapping](https://www.canva.com/design/DAGxWitsSiQ/z2GITCy5OGNM9rgG8GfzhQ/edit?utm_content=DAGxWitsSiQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton){.external target="_blank"}
* Survey of the tools:
  + Have your staff take a survey of all the tools that have been identified
  + Have them self identify the role that they use the tool from:
    - Organizers / Staff
    - Leaders
    - Managers
    - Admin
  + Then have people answer the following questions (for each tool):
    - On a scale of 1 to 10, 1 being never heard of it, 10 being that you use it all the time; **How familiar are you with this tool?**
    - On a scale of 1 to 10, 1 being not useful at all, 10 being extremely useful; **How useful is this tool to your workflow?**
    - **Do you use an alternative tool instead of this tool for the purpose it provides? If so, what is that tool, and why do you use it?**
* Discussion with organizers about tool usage:
  + We recommend this being a separate call so that the conversations are able to have the time they need for solid discussion.
  + Questions:
    - **What are your current practices around data entry and measuring power/leadership development?** *What is hard about tracking and measuring your base? How is the organizing culture of the organization set up to support this rigor? How might it not be?*
    - **Are you tracking your base in your database or at least on paper? What metrics or data points are you tracking about leadership?** *Are you propositioning people in powerful ways? Are you doing many 1:1s? And are you tracking this data somewhere? Are you tracking too much or too little?*
    - **What is your current user rate for your tool stack and culture of practice to use these tools?**
      * *What currently does and does not work with your current tool stack?*
      * *What is the level of usage of the tools for your base building/organizing?*
      * *What is getting in the way? (time, training, accountability etc)*




